{
 "title": "Pi-Hole data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Queries today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_dns_queries_today", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queries blocked today",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_blocked_today", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Percentage blocked",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_ads_percentage_today", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Domains on lists",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_domains_being_blocked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Queries cached/forwarded",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "pihole_queries_cached", "legendFormat": "Queries cached" },
    { "expr": "pihole_queries_forwarded", "legendFormat": "Queries forwarded" }
   ]
  },
  {
   "title": "Top 10 queries by domain",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 3 },
   "targets": [
    { "expr": "topk(10, pihole_top_queries)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_querytypes", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Upstream servers",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pihole_forward_destinations", "legendFormat": "{{destination_name}}" }
   ]
  },
  {
   "title": "Total queries",
   "type": "timeseries",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(delta(pihole_ads_blocked_today[10m])))",
     "legendFormat": "Blocked"
    },
    {
     "expr": "sum(round(delta(pihole_queries_forwarded[10m])))",
     "legendFormat": "Permitted"
    }
   ]
  },
  {
   "title": "Top 10 blocked domains",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 14 },
   "targets": [
    { "expr": "topk(10, pihole_top_ads)", "legendFormat": "{{ domain }}" }
   ]
  },
  {
   "title": "Client Activity",
   "type": "timeseries",
   "description": "Because this graph does a delta between the current and previous 10 minutes it will take 20 minutes before you start seeing data.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(round(delta(pihole_top_sources[10m]))) by (source)>0",
     "legendFormat": "{{source}}"
    }
   ]
  }
 ]
}